### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by AlecksJohanssen** [huydangquoc/myblog#1]
Hi Huy Dang, thank you for taking time doing this <3 .
### Some cool stuffs:
- Good article validations
- Nice UI polished
- The code looks clean, but next time remember to tab only 2 indent.
  Overall this app looks good, but I suggest you finish 1 last optional .

**Comment by huydangquoc** [comment]
Hi @AlecksJohanssen,
Thank you for your feedback 👍
